spring:
  application:
    name: pix-service

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/pixdb
    username: pixuser
    password: pixpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 #numero maximo de conexoes
      minimum-idle: 2 #conexoes ociosas minimas
      connection-timeout: 30000 #Tempo máximo de espera para uma conexão (30 seg)
      idle-timeout: 600000 #Tempo máximo de inatividade (5 min)
      max-lifetime: 1800000 #Tempo máximo de vida útil de uma conexão (20 min)

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.elton.pixservice: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
